spring.application.name=Web-1

spring.datasource.url=jdbc:postgresql://localhost:5432/test-db
spring.datasource.username=test-user
spring.datasource.password=test-pass
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true